// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-fh1aV0cOpVii8DXZERqYwXMrbtCB6A',
    appId: '1:569363973691:web:79c3d163ced6f37290be1e',
    messagingSenderId: '569363973691',
    projectId: 'apptkb-306c7',
    authDomain: 'apptkb-306c7.firebaseapp.com',
    storageBucket: 'apptkb-306c7.firebasestorage.app',
    measurementId: 'G-3YLFQNBDFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0WpOO0u9zJD0-w1BPEHjwEAscErysdzs',
    appId: '1:569363973691:android:8126ab8078cad2b690be1e',
    messagingSenderId: '569363973691',
    projectId: 'apptkb-306c7',
    storageBucket: 'apptkb-306c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09BY1Md93fAMKGwv_dMRQdxuIAHCYiCQ',
    appId: '1:569363973691:ios:1394f29b4e8e03ab90be1e',
    messagingSenderId: '569363973691',
    projectId: 'apptkb-306c7',
    storageBucket: 'apptkb-306c7.firebasestorage.app',
    iosBundleId: 'com.example.workScheduleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09BY1Md93fAMKGwv_dMRQdxuIAHCYiCQ',
    appId: '1:569363973691:ios:1394f29b4e8e03ab90be1e',
    messagingSenderId: '569363973691',
    projectId: 'apptkb-306c7',
    storageBucket: 'apptkb-306c7.firebasestorage.app',
    iosBundleId: 'com.example.workScheduleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8-fh1aV0cOpVii8DXZERqYwXMrbtCB6A',
    appId: '1:569363973691:web:ecbbf1958a44e9be90be1e',
    messagingSenderId: '569363973691',
    projectId: 'apptkb-306c7',
    authDomain: 'apptkb-306c7.firebaseapp.com',
    storageBucket: 'apptkb-306c7.firebasestorage.app',
    measurementId: 'G-LDYK54VYLJ',
  );
}
